---
name: Prateek's Blog
givenName: Prateek
author: Prateek Surana
url: "https://prateeksurana.me/"
social:
  twitter: "https://twitter.com/psuranas"
  github: "https://github.com/prateek3255"
  stackOverflow: "https://stackoverflow.com/users/8252081/prateek-surana"
  medium: "https://medium.com/@prateeksurana3255"
  quora: "https://www.quora.com/profile/Prateek-Surana-11"
  linkedIn: "https://www.linkedin.com/in/psuranas/"
